const RECETAS = [
  // Aperitivos (40)
  {titulo:"Tostas de tomate y jamón", categoria:"Aperitivo"},
  {titulo:"Tostas de anchoa y pimiento", categoria:"Aperitivo"},
  {titulo:"Tostas de escalivada", categoria:"Aperitivo"},
  {titulo:"Tostas de salmón y queso fresco", categoria:"Aperitivo"},
  {titulo:"Croquetas de jamón", categoria:"Aperitivo"},
  {titulo:"Croquetas de pollo", categoria:"Aperitivo"},
  {titulo:"Croquetas de bacalao", categoria:"Aperitivo"},
  {titulo:"Croquetas de setas", categoria:"Aperitivo"},
  {titulo:"Empanadillas de atún", categoria:"Aperitivo"},
  {titulo:"Empanadillas de carne", categoria:"Aperitivo"},
  {titulo:"Patatas bravas", categoria:"Aperitivo"},
  {titulo:"Patatas alioli", categoria:"Aperitivo"},
  {titulo:"Boquerones en vinagre", categoria:"Aperitivo"},
  {titulo:"Champiñones al ajillo", categoria:"Aperitivo"},
  {titulo:"Gildas donostiarras", categoria:"Aperitivo"},
  {titulo:"Pinchos de tortilla", categoria:"Aperitivo"},
  {titulo:"Pinchos morunos", categoria:"Aperitivo"},
  {titulo:"Queso marinado en aceite", categoria:"Aperitivo"},
  {titulo:"Hummus clásico con crudités", categoria:"Aperitivo"},
  {titulo:"Hummus de remolacha", categoria:"Aperitivo"},
  {titulo:"Hummus de aguacate", categoria:"Aperitivo"},
  {titulo:"Gazpacho en vasitos", categoria:"Aperitivo"},
  {titulo:"Salmorejo en chupitos", categoria:"Aperitivo"},
  {titulo:"Ensaladilla rusa", categoria:"Aperitivo"},
  {titulo:"Tortilla francesa mini", categoria:"Aperitivo"},
  {titulo:"Banderillas variadas", categoria:"Aperitivo"},
  {titulo:"Mejillones en escabeche", categoria:"Aperitivo"},
  {titulo:"Sardinas marinadas", categoria:"Aperitivo"},
  {titulo:"Pulpo a la gallega (tapa)", categoria:"Aperitivo"},
  {titulo:"Calamares a la romana", categoria:"Aperitivo"},
  {titulo:"Torreznos crujientes", categoria:"Aperitivo"},
  {titulo:"Jamón con picos", categoria:"Aperitivo"},
  {titulo:"Queso manchego con membrillo", categoria:"Aperitivo"},
  {titulo:"Pimientos del padrón", categoria:"Aperitivo"},
  {titulo:"Montadito de lomo", categoria:"Aperitivo"},
  {titulo:"Montadito de pringá", categoria:"Aperitivo"},
  {titulo:"Bonito con tomate (tapa)", categoria:"Aperitivo"},
  {titulo:"Pisto con huevo (tapa)", categoria:"Aperitivo"},
  {titulo:"Chistorra a la sidra", categoria:"Aperitivo"},
  {titulo:"Berenjena frita con miel", categoria:"Aperitivo"},

  // Primeros (40)
  {titulo:"Sopa de ajo", categoria:"Primero"},
  {titulo:"Sopa castellana", categoria:"Primero"},
  {titulo:"Gazpacho andaluz", categoria:"Primero"},
  {titulo:"Salmorejo cordobés", categoria:"Primero"},
  {titulo:"Ajoblanco", categoria:"Primero"},
  {titulo:"Crema de calabaza", categoria:"Primero"},
  {titulo:"Crema de puerros", categoria:"Primero"},
  {titulo:"Crema de champiñón", categoria:"Primero"},
  {titulo:"Pisto manchego", categoria:"Primero"},
  {titulo:"Menestra de verduras", categoria:"Primero"},
  {titulo:"Lentejas estofadas", categoria:"Primero"},
  {titulo:"Garbanzos con espinacas", categoria:"Primero"},
  {titulo:"Judías blancas con verduras", categoria:"Primero"},
  {titulo:"Arroz caldoso de verduras", categoria:"Primero"},
  {titulo:"Arroz a la cubana", categoria:"Primero"},
  {titulo:"Arroz negro", categoria:"Primero"},
  {titulo:"Arroz al horno", categoria:"Primero"},
  {titulo:"Paella de verduras", categoria:"Primero"},
  {titulo:"Fideuá de pescado", categoria:"Primero"},
  {titulo:"Macarrones con tomate", categoria:"Primero"},
  {titulo:"Tallarines al ajillo", categoria:"Primero"},
  {titulo:"Espaguetis carbonara ligera", categoria:"Primero"},
  {titulo:"Ensalada mixta", categoria:"Primero"},
  {titulo:"Ensalada campera", categoria:"Primero"},
  {titulo:"Ensalada de garbanzos", categoria:"Primero"},
  {titulo:"Ensalada de pasta fría", categoria:"Primero"},
  {titulo:"Tomates aliñados", categoria:"Primero"},
  {titulo:"Papas arrugadas con mojo", categoria:"Primero"},
  {titulo:"Pimientos asados", categoria:"Primero"},
  {titulo:"Alcachofas salteadas", categoria:"Primero"},
  {titulo:"Acelgas rehogadas", categoria:"Primero"},
  {titulo:"Sopa de pescado", categoria:"Primero"},
  {titulo:"Caldo gallego", categoria:"Primero"},
  {titulo:"Cocido andaluz (sopa)", categoria:"Primero"},
  {titulo:"Sopa minestrone", categoria:"Primero"},
  {titulo:"Vichyssoise", categoria:"Primero"},
  {titulo:"Crema de zanahoria", categoria:"Primero"},
  {titulo:"Porrusalda", categoria:"Primero"},
  {titulo:"Sopa de marisco", categoria:"Primero"},
  {titulo:"Caldo de pollo casero", categoria:"Primero"},

  // Segundos (40)
  {titulo:"Pollo al ajillo", categoria:"Segundo"},
  {titulo:"Pollo al horno con patatas", categoria:"Segundo"},
  {titulo:"Pollo en pepitoria", categoria:"Segundo"},
  {titulo:"Pechuga de pollo a la plancha", categoria:"Segundo"},
  {titulo:"Escalope de ternera", categoria:"Segundo"},
  {titulo:"Filete de ternera a la plancha", categoria:"Segundo"},
  {titulo:"Carrilleras al vino tinto", categoria:"Segundo"},
  {titulo:"Rabo de toro", categoria:"Segundo"},
  {titulo:"Albóndigas en salsa", categoria:"Segundo"},
  {titulo:"Lomo adobado", categoria:"Segundo"},
  {titulo:"Costillas al horno", categoria:"Segundo"},
  {titulo:"Chuletillas de cordero", categoria:"Segundo"},
  {titulo:"Cordero asado", categoria:"Segundo"},
  {titulo:"Secreto ibérico a la plancha", categoria:"Segundo"},
  {titulo:"Solomillo al roquefort", categoria:"Segundo"},
  {titulo:"Bacalao a la vizcaína", categoria:"Segundo"},
  {titulo:"Bacalao al pil-pil", categoria:"Segundo"},
  {titulo:"Merluza en salsa verde", categoria:"Segundo"},
  {titulo:"Dorada al horno", categoria:"Segundo"},
  {titulo:"Lubina a la sal", categoria:"Segundo"},
  {titulo:"Salmón al papillote", categoria:"Segundo"},
  {titulo:"Atún encebollado", categoria:"Segundo"},
  {titulo:"Calamares en su tinta", categoria:"Segundo"},
  {titulo:"Pulpo a la gallega", categoria:"Segundo"},
  {titulo:"Paella mixta", categoria:"Segundo"},
  {titulo:"Arroz con pollo", categoria:"Segundo"},
  {titulo:"Arroz con bogavante", categoria:"Segundo"},
  {titulo:"Empanada gallega de atún", categoria:"Segundo"},
  {titulo:"Pisto con huevos", categoria:"Segundo"},
  {titulo:"Tortilla de patatas", categoria:"Segundo"},
  {titulo:"Revuelto de setas", categoria:"Segundo"},
  {titulo:"Conejo al ajillo", categoria:"Segundo"},
  {titulo:"Codornices escabechadas", categoria:"Segundo"},
  {titulo:"Callos a la madrileña", categoria:"Segundo"},
  {titulo:"Fabada asturiana", categoria:"Segundo"},
  {titulo:"Marmitako de bonito", categoria:"Segundo"},
  {titulo:"Chuletón a la plancha", categoria:"Segundo"},
  {titulo:"Escabeche de caballa", categoria:"Segundo"},
  {titulo:"Bonito con tomate", categoria:"Segundo"},
  {titulo:"Trucha a la navarra", categoria:"Segundo"},

  // Postres (40)
  {titulo:"Flan casero", categoria:"Postre"},
  {titulo:"Natillas caseras", categoria:"Postre"},
  {titulo:"Arroz con leche", categoria:"Postre"},
  {titulo:"Leche frita", categoria:"Postre"},
  {titulo:"Torrijas", categoria:"Postre"},
  {titulo:"Crema catalana", categoria:"Postre"},
  {titulo:"Tarta de queso al horno", categoria:"Postre"},
  {titulo:"Tarta de Santiago", categoria:"Postre"},
  {titulo:"Bizcocho de yogur", categoria:"Postre"},
  {titulo:"Bizcocho de naranja", categoria:"Postre"},
  {titulo:"Magdalenas caseras", categoria:"Postre"},
  {titulo:"Galletas de mantequilla", categoria:"Postre"},
  {titulo:"Rosquillas fritas", categoria:"Postre"},
  {titulo:"Pestiños", categoria:"Postre"},
  {titulo:"Buñuelos de viento", categoria:"Postre"},
  {titulo:"Filloas", categoria:"Postre"},
  {titulo:"Peras al vino", categoria:"Postre"},
  {titulo:"Compota de manzana", categoria:"Postre"},
  {titulo:"Macedonia de frutas", categoria:"Postre"},
  {titulo:"Helado rápido de plátano", categoria:"Postre"},
  {titulo:"Mousse de chocolate", categoria:"Postre"},
  {titulo:"Natillas de vainilla", categoria:"Postre"},
  {titulo:"Tarta de manzana", categoria:"Postre"},
  {titulo:"Tarta tres leches (versión)", categoria:"Postre"},
  {titulo:"Brazo de gitano", categoria:"Postre"},
  {titulo:"Quesada pasiega", categoria:"Postre"},
  {titulo:"Tocino de cielo", categoria:"Postre"},
  {titulo:"Pan de Calatrava", categoria:"Postre"},
  {titulo:"Cuajada con miel", categoria:"Postre"},
  {titulo:"Crepes dulces", categoria:"Postre"},
  {titulo:"Flan de café", categoria:"Postre"},
  {titulo:"Crema pastelera con frutas", categoria:"Postre"},
  {titulo:"Tarta de almendra", categoria:"Postre"},
  {titulo:"Tarta de galletas con chocolate", categoria:"Postre"},
  {titulo:"Bizcocho marmolado", categoria:"Postre"},
  {titulo:"Helado de yogur", categoria:"Postre"},
  {titulo:"Brownie sencillo", categoria:"Postre"},
  {titulo:"Crema de limón", categoria:"Postre"},
  {titulo:"Naranja con canela", categoria:"Postre"},
  {titulo:"Fresas con nata", categoria:"Postre"}
];
